
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  url: "postgresql://postgres:postgres@localhost: /phase-3-sinatra-react-project"


test:
  <<: *default
  url: "postgresql://postgres:postgres@localhost: /test_phase-3-sinatra-react-project"


production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>